def obter_capital(codigo):
    match codigo:
        case 1:
            return "aracaju"
        case 2:
            return "belem"
        case 3:
            return "belo_horizonte"
        case 4:
            return "boa_vista"
        case 5:
            return "brasilia"
        case 6:
            return "campo_grande"
        case 7:
            return "cuiaba"
        case 8:
            return "curitiba"
        case 9:
            return "florianopolis"
        case 10:
            return "fortaleza"
        case 11:
            return "goiania"
        case 12:
            return "joao_pessoa"
        case 13:
            return "macapa"
        case 14:
            return "maceio"
        case 15:
            return "manaus"
        case 16:
            return "natal"
        case 17:
            return "palmas"
        case 18:
            return "porto_alegre"
        case 19:
            return "porto_velho"
        case 20:
            return "recife"
        case 21:
            return "rio_branco"
        case 22:
            return "rio_de_janeiro"
        case 23:
            return "salvador"
        case 24:
            return "sao_luis"
        case 25:
            return "sao_paulo"
        case 26:
            return "teresina"
        case 27:
            return "vitoria"
        case _:
            return "Código inválido"